version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  sprouted-redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    volumes:
      - ./.redisdata:/data
