export default function Head() {
  return (
    <>
      <title>Sprouted</title>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by Me" />
      <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    </>
  );
}
